### ISSUE TITLE
restrictedUnitsData errors

### ISSUE THREAD

**Issue by CodingSquirrel** [The-Balthazar/BrewLAN#12]
Your restrictedUnitsData.lua (mods\BrewLAN\hook\lua\ui\lobby\restrictedUnitsData.lua) is incompatible with this change https://github.com/FAForever/fa/commit/6bfcea2fce577d6843d0d24768d1a4792bcbf1d3#diff-8a8d5feb7f2ed2f23cb5ec9a310a7a1c

**Comment by CodingSquirrel** [comment]
You can reproduce the errors by using the Notify mod (I tested with 3.7 and 3.8) and attempting to upgrade the tech on your commander.

**Comment by The-Balthazar** [comment]
Fixed. https://github.com/The-Balthazar/BrewLAN/commit/9df6f43db2a193071ad164431bfbeb42c2df5ed6
