### ISSUE TITLE
Experimental Icons

### ISSUE THREAD

**Issue by Saxxonknight** [The-Balthazar/BrewLAN#14]
Had a break for a bit.  Started playing again last night.  Noticed that with the Experimental Icons Overhaul the icon in mod manager is blank, to which is says it would be then improperly installed.  I checked, its in the gamedata folder.

I think I recall looking into this a while back and noticed that its possible its a case problem, ie the callout was capitalized and the file name was lower case or something to that effect.  Was a couple months ago I noted that but at the time forgot about it to post.

**Comment by The-Balthazar** [comment]
The experimental icons mod doesn't work with FAF. FAF doesn't load the SCD. Having the textures outside of the SCD would require rewriting that part of the actual UI script, and I have not yet found how to force FAF to load external SCDs.

**Comment by Saxxonknight** [comment]
Might it have to do with FAF using its own FA.EXE perhaps?  It doesn't use the game's original executable. I found that out trying to play it offline.  That may have a separate path for some of those files.

**Comment by The-Balthazar** [comment]
FaF uses a lot of the game's base files, presumably for both copyright and filesize reasons, but explicitly loads specific SCD files from the original, then loads its changes on top of them. I have not experimented with placing copies of my SCD files in **C:\ProgramData\FAForever\gamedata** directly, but that might be a work around until I find a less hap-hazard way of getting it to load my SCDs, or devising a neat way to not need the SCDs.

**Comment by Saxxonknight** [comment]
In /ProgramData/FAForever/bin/init_faf.lua I noted on my home computer that brewlan.scd etc was on the blacklist in that file.  It also has a whitelist.  I suspect that might lead to your bugbear on this.  The game executable that FAF uses is in this folder as well, its a copy of the original updated by the FAF crew to their current build.  At least on the home computer that blacklist may be creating the issues at least in part.
