### ISSUE TITLE
Upgradeable structures double build

### ISSUE THREAD

**Issue by Saxxonknight** [The-Balthazar/BrewLAN#15]
This bug is more of a game breaker.  Seen it once a long time ago, this time its a bit more ubiquitous.

If you upgrade a Mex or Factory, it will upgrade to its Tech 2 but the Tech 1 building also remains in the same spot.  You have to reclaim it to get the Factory to work, though the Tech 2 Mex appears to immediately effect production.  Engineers who are pathing to upgrade Mexes in series will immediately re-upgrade the finished Mex, essentially costing you double the upgrade cost unless you stop them and reclaim the T1 Mex on the node.

I noted this, and restarted a game only with BrewLAN, BrewUI and Experimental Icons and can confirm its between the mod and the current FAF build.

**Comment by Saxxonknight** [comment]
Also maybe related, factories are building the unit inside their model instead of on the surface or beside them as they normally would.  I suspect this is appearing because of the overlay of the phantom second factory.

**Comment by The-Balthazar** [comment]
Fixed. Also fixed a second issue that seems related, but is actually totally unrelated, related to upgrading a T1 mex all the way; possibly only outside of FaF.

**Comment by Saxxonknight** [comment]
I think its something that they changed new in FAF because the last several games I've played I get the option to upgrade Mex and Radar etc fully or partially (I think it still goes sequential, just that it will immediately start the second upgrade once first completes).

**Comment by The-Balthazar** [comment]
Is that since this update: https://github.com/The-Balthazar/BrewLAN/commit/da7f2e245dc8b91ef60a7f08a08cfdc311968a98

**Comment by Saxxonknight** [comment]
No, I would say within last few weeks.  I wasn't getting much game time for a while.
