### ISSUE TITLE
Tech1 Field Engineers gun not functioning

### ISSUE THREAD

**Issue by Saxxonknight** [The-Balthazar/BrewLAN#16]
Noticed on newest build that Wally's are not shooting enemy units.  They did in the old build I had from a couple months ago, I know that FAF has been updated since as well so between the mod and the game something got disabled or changed on that.

**Comment by Saxxonknight** [comment]
Hmm.  Several minutes into the game, one of the Wally's started shooting at enemy engineers (naturally that I was trying to capture).  So its an interment issue.

**Comment by The-Balthazar** [comment]
Probably fixed: https://github.com/The-Balthazar/BrewLAN/commit/af2ce88489f984a51c80acee291bedc28f71d0ca
Not fully tested, but unit no longer logs a script error.

**Comment by Saxxonknight** [comment]
I'll give it a try in next couple days.
