### ISSUE TITLE
Some units don't have a Faction Name and crashes FAF Game

### ISSUE THREAD

**Issue by Uveso** [The-Balthazar/BrewLAN#22]
Please add faction names to all units :)

temporary fix can be found here:
http://forums.faforever.com/viewtopic.php?f=3&t=15002&p=153183#p153183

FAF game will add a fail save for units without faction in the next patch:
https://github.com/FAForever/fa/pull/2150

**Comment by The-Balthazar** [comment]
I meant to push this a while ago, but faction names: https://github.com/The-Balthazar/BrewLAN/commit/8edc35bfd2baa2e3d71c534340d37d29a0528966
