### ISSUE TITLE
Current build BrewLAN vs FAF not loading

### ISSUE THREAD

**Issue by Saxxonknight** [The-Balthazar/BrewLAN#23]
Using only BrewLAN and BrewUI I start a game on the current FAF build and you get on the map, it has one mass point and no units.  Seen this before with a lot of mods in a game, but I boilded it down to just BrewLAN and it persisted.

**Comment by Luxcervinae** [comment]
Hey! I've had this issue recently and i posted on the Faf forums about it, search through recent posts in the technical help part and you should find a post by me, uveso fixed the issue in it.

**Comment by Saxxonknight** [comment]
I'll give it a go.  I also found the issue using a vanilla install with other UI mods later that night as well.  (Ecomanager, Supreme Economy, Sequential Extractors etc).  Was playing around with trying different combos to work but ran out of time before work.

**Comment by Saxxonknight** [comment]
Tried it, didn't work, still getting blank map with just FAF and BrewLAN.

**Comment by Kaitane** [comment]
Hey Saxxonknight. 
What version of BrewLan are you using with FAF? At this stage, FAF only works with the current BrewLan public release of version 0.7.5.5 betaon Moddb. You will still get the blank map/etc on FAF if you use any unreleased BrewLan build, such as the current 0.7.9. 

Uveso's fix is only designed to work with the  current public release on Moddb. I had the same problem as you did until I installed v 0.7.5.5 beta. I'm also using the FAF mods you mentioned with no problem.
