### ISSUE TITLE
BrewLan And FAF

### ISSUE THREAD

**Issue by Pop000100** [The-Balthazar/BrewLAN#24]
https://github.com/FAForever/fa/issues/2243 i opened this issue and never got a response is it because they don't want to support mods?

**Comment by The-Balthazar** [comment]
0.7.5.5 is 2 years old. Update to the dev version here on GitHub. There is also a very recent version uploaded to the FAF vault by PhilipJFry which is listed as version 79. Post any issues with those versions so I can address them for the upcoming 0.8 release.
