### ISSUE TITLE
Brewlan V81 doesn't seem to function properly with FAF

### ISSUE THREAD

**Issue by KoRaLLL** [The-Balthazar/BrewLAN#26]
I'm not sure if this is a Brewlan issue or a FAF issue, but when you download it from the mod vault, it doesn't seem to recognise the mod as downloaded

The title of the mod doesn't turn green like every other mod does when you click 'download' and whenever you boot a FAF game with Brewlan activated it will force any players joining to re-download it despite those players already having the mod downloaded

It's like FAF isn't recognising the directory or something properly

**Comment by KoRaLLL** [comment]
I just saw that FAF doesn't have the latest version of Brewlan, is 0.8.2 coming to FAF or no?

**Comment by The-Balthazar** [comment]
That sounds like a FAF issue.
0.8.2 is an intermediary development version. The latest "released" versions are 0.8 and 0.81.
