### ISSUE TITLE
Issue with Sorian Adaptive AIx + Research & Daiquiris 

### ISSUE THREAD

**Issue by Renegade1993** [The-Balthazar/BrewLAN#30]
Hey Balthazar,

I am playing around with the git version as it was on the 3rd. 

I found that using Research & Daiquiris causes the AI to be unable to research/use anything beyond what is available in the tier 1 tab of the research facility. They can get to t2, which i suspect is only because t2 is the last thing you can access in the t1 tab and somehow the AI isn't able to use the second tab's functionality.

I ran a test with just the advanced ai mod, base brewlan, and research and daiquiris with two sorian adaptive aix's pitted against each other. After 30 minutes, neither were able to build anything beyond t2 with 2.0 cheat and build speed modifiers. 

I ran another test with my very exhaustive mod list (24 sim + 1ui mod) without research and daiquiris.  This time the AI had several t3 buildings before the 20 minute mark. 

Just wanted to make sure you had tabs on this issue. 

Keep up the fantastic work, and many thanks!

**Comment by The-Balthazar** [comment]
By advanced ai mod do you mean the BrewLAN AI stuff included, or some external mod?

I reasonably recently fixed an issue where if more than one AI had the same faction they overwrote each others research information, so I'm not sure if it's related to that.

**Comment by The-Balthazar** [comment]
Oh I believe I've identified the issue; the research centre is getting caught in an upgrade loop.

**Comment by The-Balthazar** [comment]
Code inserted to prevent AIs that couldn't track limited builds correctly from accidentally building multiple research centres was preventing them from being able to upgrade.

It has been resolved: https://github.com/The-Balthazar/BrewLAN/commit/d4dfd5f4e79dd95deb8b38662504d590638e3351
