### ISSUE TITLE
Seraphim Aezhou T3 Sonar Platform issue

### ISSUE THREAD

**Issue by Kaitane** [The-Balthazar/BrewLAN#33]
Unable to build the Seraphim T3 Sonar Platform. The icon appears in the build menu, and no information appears when you hover the mouse pointer over it; unlike other unit/building icons that do. This problem only appears in FAF. Seems to work ok in the Steam version. Not running any other mods for test purposes. I only use your latest GitHub versions. This has been an issue for some months. The problem also existed before the latest FAF patch.

**Comment by The-Balthazar** [comment]
Not a BrewLAN issue: https://github.com/FAForever/fa/issues/3485
