### ISSUE TITLE
In game icons not showing

### ISSUE THREAD

**Issue by avatat1995** [The-Balthazar/BrewLAN#34]
Hello!
Firstly, thank you for all your hard work and hours of entertainment.

I installed BrewLan a few months back and it was all working perfectly. I did a fresh install to give LOUD a try, but having played BrewLan as a standalone I much preferred that. So I again did a totally fresh install and installed the latest update 0.8.9.9

This time when booting up the game, none of the in game icons are present like before. I just see the blue square with the generic "In progress" text.

I don't remember needing another mod for the icons on my first install, have I done something wrong? I installed via Zip, simple drag and merge using WinRAR. All folder roots are as they should be and every other aspect of the mods work perfectly - just no icons.

Thanks in advance!

**Comment by avatat1995** [comment]
Just to clarify - I mean in game unit/building icons on the HUD.

**Comment by The-Balthazar** [comment]
`brewlan.scd` contains the unit icons and needs to be in the gamedata folder in the games install directory. Check the [verification section of the install doc](https://github.com/The-Balthazar/BrewLAN/wiki/Installation#verification).

**Comment by avatat1995** [comment]
I do apologize for wasting your time. All these years modding and I hadn't extracted Game Data correctly!
Thanks for the helping to call out my idiocy haha
