### ISSUE TITLE
Problem with German Translation

### ISSUE THREAD

**Issue by SchwererKreuzer** [The-Balthazar/BrewLAN#35]
The German translation is not working.
There is a wrong entrys in the German translation, in lines 595.
To many new lines.

Wrong:
![wrong](https://user-images.githubusercontent.com/18217263/159178395-545f4595-9324-4e49-a6f7-2112245f4bdf.JPG)

Correct:
![correct](https://user-images.githubusercontent.com/18217263/159178405-56310cb3-3f04-4207-9c7e-abf9bf9b5d61.JPG)

[strings_db german working.zip](https://github.com/The-Balthazar/BrewLAN/files/8311961/strings_db.german.working.zip)

**Comment by SchwererKreuzer** [comment]
active_mods = {
    ['25D57D85-7D84-27HT-A501-BR3WAI0000000'] = true,
    ['74A9EAB2-E851-11DB-A1F1-F2C755D89593'] = true,
    ['Z529ea71-93ef-41a6-b552-STRATICON00010'] = true,
    ['25D57D85-9JA7-D842-BREW-SHIELDS000006'] = true,
    ['25D57D85-7D84-27HT-A501-BR3WL4N0000899'] = true,
    ['16678e1e-7fc9-11e5-8bcf-waterguard11'] = true,
    ['25D57D85-7D84-27HT-A501-BR3WUIET00003'] = true

With this tested mods the german translation works.
-------------------
added this mod:
['25D57D85-9JA7-D842-BREW-TURRETS000003'] = true,

The Game is in english:

![error](https://user-images.githubusercontent.com/18217263/159363006-08a6384c-3539-4965-a7b9-067202d13c24.png)

**Comment by The-Balthazar** [comment]
This is resolved on the [moddb mirror](https://www.moddb.com/mods/brewlan/downloads/brewlan-0899) as of two weeks ago. The github release of the fix is currently held up by some other unrelated changes that I don't want to release yet.

**Comment by SchwererKreuzer** [comment]
Thanks, the version from moddb works.

**Comment by The-Balthazar** [comment]
No problem. Future versions shouldn't have these issues; I implemented changes to the translation export process that has error checking and fixing, and an additional verification process.
