### ISSUE TITLE
brew lan causes UEF experimentals to be invisible

### ISSUE THREAD

**Issue by thecatblue** [The-Balthazar/BrewLAN#38]
sense installing the BREW LAN mod pack the UEF experimental units have all become invisible. it DOES NOT cause any gameplay issues other than not seeing the units and needing to track them with the map markers and the hail of fire from their guns when near the enemy.

is there a way to fix this or is the UEF just going to have a ghost army forever?

all other factions work 100% properly and the mod is a blast to run!

**Comment by The-Balthazar** [comment]
I'm going to need more information to work out what's going wrong for you.
Which version of the game are you running, which version of BrewLAN are you running, do you have any other mods active, what're your graphics settings, does the log say anything, and are you sure you installed correctly?

**Comment by thecatblue** [comment]
hey sorry for the super late reply. I'm running brew LAN 0.8.9.9with supreme commander 1.6.6I don't have any other mods installed, but am not 100% sure i installed the files properly as i have never done mods before, but I did fallow the included instructions to the best of my ability. how do i view the logs? ill se if i can find them and ill get them to you.the video settings are:
primary adapter: 1280x1024(60)fidelity presets: highrender sky: onfidelity: highshadow fidelity: mediumanti-aliasing: 2texture detail: highLevel of detail: highv-sync: onbloom render: on    On Wednesday, March 1, 2023 at 09:10:11 AM EST, Sean Wheeldon ***@***.***> wrote:  
 
 


I'm going to need more information to work out what's going wrong for you.
Which version of the game are you running, which version of BrewLAN are you running, do you have any other mods active, what're your graphics settings, does the log say anything, and are you sure you installed correctly?

**Comment by The-Balthazar** [comment]
if you use the launch command `/Log "gamelog.log"` it will create a log file in the game directory. Post that log and I'll probably be able to diagnose the issue.

**Comment by thecatblue** [comment]
it took me a bit but i figured it out. let me know if there is anything else i can send to help!
    On Thursday, April 6, 2023 at 06:13:55 PM EDT, Sean Wheeldon ***@***.***> wrote:  
 
 


if you use the launch command /Log "gamelog.log" it will create a log file in the game directory. Post that log and I'll probably be able to diagnose the issue.

**Comment by thecatblue** [comment]
i had activated a mod from brew LAN that was something to do with camouflage today. i noticed that it said it activated certain files reskins and meshes.  after activating it the UEF experimentals are no longer invisible. I'm gonna run through each faction to see if it affected any of them negatively, and once im done making each of the uef units in my skirmish, ill send you the name of the mod pack responsible
i feel stupid, i could have fixed it by activating another mod in the pack
    On Thursday, April 6, 2023 at 06:29:58 PM EDT, Sean Drake ***@***.***> wrote:  
 
  it took me a bit but i figured it out. let me know if there is anything else i can send to help!
    On Thursday, April 6, 2023 at 06:13:55 PM EDT, Sean Wheeldon ***@***.***> wrote:  
 
 


if you use the launch command /Log "gamelog.log" it will create a log file in the game directory. Post that log and I'll probably be able to diagnose the issue.

**Comment by thecatblue** [comment]
the mod pack "expert camo" ironically fixed the invisibility issue, and didn't affect any factions units negatively. sorry for taking up your time for something i could have fixed myself if i really took my time and looked through things.
and thanks for brew LAN it made forged alliances so much better!
    On Thursday, April 6, 2023 at 07:06:08 PM EDT, Sean Drake ***@***.***> wrote:  
 
  i had activated a mod from brew LAN that was something to do with camouflage today. i noticed that it said it activated certain files reskins and meshes.  after activating it the UEF experimentals are no longer invisible. I'm gonna run through each faction to see if it affected any of them negatively, and once im done making each of the uef units in my skirmish, ill send you the name of the mod pack responsible
i feel stupid, i could have fixed it by activating another mod in the pack
    On Thursday, April 6, 2023 at 06:29:58 PM EDT, Sean Drake ***@***.***> wrote:  
 
  it took me a bit but i figured it out. let me know if there is anything else i can send to help!
    On Thursday, April 6, 2023 at 06:13:55 PM EDT, Sean Wheeldon ***@***.***> wrote:  
 
 


if you use the launch command /Log "gamelog.log" it will create a log file in the game directory. Post that log and I'll probably be able to diagnose the issue.
