### ISSUE TITLE
Conflict with Blackops Unleashed in FAF

### ISSUE THREAD

**Issue by Wolski2000** [The-Balthazar/BrewLAN#40]
When launching the game with both Blackops Unleashed and BrewLAN the game gets stuck in the loading screen.

FAF log file provided below.
[game_19871084.log](https://github.com/The-Balthazar/BrewLAN/files/11375604/game_19871084.log)

**Comment by The-Balthazar** [comment]
BlackOps issue, not BrewLAN issue. https://github.com/Uveso/BlackOpsFAF-Unleashed/pull/5

**Comment by Uveso** [comment]
@The-Balthazar 
Thank you for providing a patch for Black Ops!

@Wolski2000 
BlackOpsFAF-Unleashed version 22 is out with a fix.
Please let us know if it works for you.
